-- Auto-generated FK constraints.
-- FKs into auth.users (Supabase) are emitted as comments; replace with your app's users table FK if applicable.

-- (auth.users ref) ALTER TABLE `admin_settings` ADD CONSTRAINT `admin_settings_updated_by_fkey` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`);
ALTER TABLE `ai_case_evaluations` ADD CONSTRAINT `ai_case_evaluations_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_case_evaluations` ADD CONSTRAINT `ai_case_evaluations_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_decision_consents` ADD CONSTRAINT `ai_decision_consents_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_decision_consents` ADD CONSTRAINT `ai_decision_consents_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_decision_consents` ADD CONSTRAINT `ai_decision_consents_transparency_log_id_fkey` FOREIGN KEY (`transparency_log_id`) REFERENCES `ai_transparency_logs` (`id`) ON DELETE SET NULL;
ALTER TABLE `ai_feedback` ADD CONSTRAINT `ai_feedback_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `meta_campaigns` (`id`) ON DELETE SET NULL;
ALTER TABLE `ai_feedback` ADD CONSTRAINT `ai_feedback_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_lead_scores` ADD CONSTRAINT `ai_lead_scores_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_lead_scores` ADD CONSTRAINT `ai_lead_scores_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_performance_snapshots` ADD CONSTRAINT `ai_performance_snapshots_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `meta_campaigns` (`id`) ON DELETE SET NULL;
ALTER TABLE `ai_performance_snapshots` ADD CONSTRAINT `ai_performance_snapshots_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_tool_results` ADD CONSTRAINT `ai_tool_results_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_transparency_logs` ADD CONSTRAINT `ai_transparency_logs_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `ai_transparency_logs` ADD CONSTRAINT `ai_transparency_logs_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `alert_notifications` ADD CONSTRAINT `alert_notifications_alert_rule_id_fkey` FOREIGN KEY (`alert_rule_id`) REFERENCES `alert_rules` (`id`) ON DELETE SET NULL;
ALTER TABLE `alert_notifications` ADD CONSTRAINT `alert_notifications_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `alert_rules` ADD CONSTRAINT `alert_rules_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `audience_profiles` ADD CONSTRAINT `audience_profiles_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `audit_logs` ADD CONSTRAINT `audit_logs_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL;
ALTER TABLE `autopilot_logs` ADD CONSTRAINT `autopilot_logs_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `meta_campaigns` (`id`) ON DELETE SET NULL;
ALTER TABLE `autopilot_logs` ADD CONSTRAINT `autopilot_logs_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `autopilot_logs` ADD CONSTRAINT `autopilot_logs_rule_id_fkey` FOREIGN KEY (`rule_id`) REFERENCES `autopilot_rules` (`id`) ON DELETE CASCADE;
ALTER TABLE `autopilot_rules` ADD CONSTRAINT `autopilot_rules_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `meta_campaigns` (`id`) ON DELETE CASCADE;
ALTER TABLE `autopilot_rules` ADD CONSTRAINT `autopilot_rules_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `budget_reallocation_logs` ADD CONSTRAINT `budget_reallocation_logs_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `meta_campaigns` (`id`) ON DELETE CASCADE;
ALTER TABLE `budget_reallocation_logs` ADD CONSTRAINT `budget_reallocation_logs_from_ad_set_id_fkey` FOREIGN KEY (`from_ad_set_id`) REFERENCES `meta_ad_sets` (`id`);
ALTER TABLE `budget_reallocation_logs` ADD CONSTRAINT `budget_reallocation_logs_to_ad_set_id_fkey` FOREIGN KEY (`to_ad_set_id`) REFERENCES `meta_ad_sets` (`id`);
ALTER TABLE `campaigns` ADD CONSTRAINT `campaigns_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `case_simulations` ADD CONSTRAINT `case_simulations_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `case_simulations` ADD CONSTRAINT `case_simulations_judge_id_fkey` FOREIGN KEY (`judge_id`) REFERENCES `judge_profiles` (`id`);
ALTER TABLE `case_simulations` ADD CONSTRAINT `case_simulations_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`);
ALTER TABLE `category_select_events` ADD CONSTRAINT `category_select_events_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE SET NULL;
ALTER TABLE `chat_conversations` ADD CONSTRAINT `chat_conversations_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `chat_messages` ADD CONSTRAINT `chat_messages_conversation_id_fkey` FOREIGN KEY (`conversation_id`) REFERENCES `chat_conversations` (`id`) ON DELETE CASCADE;
ALTER TABLE `chat_participants` ADD CONSTRAINT `chat_participants_conversation_id_fkey` FOREIGN KEY (`conversation_id`) REFERENCES `chat_conversations` (`id`) ON DELETE CASCADE;
ALTER TABLE `competitor_ad_creatives` ADD CONSTRAINT `competitor_ad_creatives_run_id_fkey` FOREIGN KEY (`run_id`) REFERENCES `competitor_ad_runs` (`id`) ON DELETE CASCADE;
ALTER TABLE `consent_logs` ADD CONSTRAINT `consent_logs_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `contacts` ADD CONSTRAINT `contacts_duplicate_of_fkey` FOREIGN KEY (`duplicate_of`) REFERENCES `contacts` (`id`) ON DELETE SET NULL;
ALTER TABLE `contacts` ADD CONSTRAINT `contacts_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `contacts` ADD CONSTRAINT `contacts_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL;
ALTER TABLE `contacts` ADD CONSTRAINT `contacts_source_id_fkey` FOREIGN KEY (`source_id`) REFERENCES `lead_sources` (`id`) ON DELETE SET NULL;
ALTER TABLE `creative_studio_projects` ADD CONSTRAINT `creative_studio_projects_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `crm_integrations` ADD CONSTRAINT `crm_integrations_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `crm_sync_logs` ADD CONSTRAINT `crm_sync_logs_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`);
ALTER TABLE `crm_sync_logs` ADD CONSTRAINT `crm_sync_logs_integration_id_fkey` FOREIGN KEY (`integration_id`) REFERENCES `crm_integrations` (`id`) ON DELETE CASCADE;
ALTER TABLE `crm_sync_logs` ADD CONSTRAINT `crm_sync_logs_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`);
ALTER TABLE `cross_platform_campaigns` ADD CONSTRAINT `cross_platform_campaigns_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `dark_funnel_visitors` ADD CONSTRAINT `dark_funnel_visitors_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `dark_funnel_visitors` ADD CONSTRAINT `dark_funnel_visitors_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`);
ALTER TABLE `document_analyses` ADD CONSTRAINT `document_analyses_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `document_analyses` ADD CONSTRAINT `document_analyses_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `document_signatures` ADD CONSTRAINT `document_signatures_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `document_signatures` ADD CONSTRAINT `document_signatures_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `dynamic_landing_pages` ADD CONSTRAINT `dynamic_landing_pages_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`);
ALTER TABLE `dynamic_landing_pages` ADD CONSTRAINT `dynamic_landing_pages_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `evidence_audit_trail` ADD CONSTRAINT `evidence_audit_trail_evidence_id_fkey` FOREIGN KEY (`evidence_id`) REFERENCES `evidence_vault` (`id`) ON DELETE CASCADE;
ALTER TABLE `evidence_vault` ADD CONSTRAINT `evidence_vault_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `evidence_vault` ADD CONSTRAINT `evidence_vault_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`);
ALTER TABLE `filter_rejection_logs` ADD CONSTRAINT `filter_rejection_logs_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE SET NULL;
ALTER TABLE `firm_benchmarks` ADD CONSTRAINT `firm_benchmarks_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `firm_branding` ADD CONSTRAINT `firm_branding_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `firm_encryption_keys` ADD CONSTRAINT `firm_encryption_keys_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `firm_encryption_keys` ADD CONSTRAINT `firm_encryption_keys_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
ALTER TABLE `firm_members` ADD CONSTRAINT `firm_members_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `firm_members` ADD CONSTRAINT `firm_members_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
ALTER TABLE `firms` ADD CONSTRAINT `firms_vertical_id_fkey` FOREIGN KEY (`vertical_id`) REFERENCES `industry_verticals` (`id`);
ALTER TABLE `fraud_checks` ADD CONSTRAINT `fraud_checks_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `geofence_campaigns` ADD CONSTRAINT `geofence_campaigns_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `gmb_posts` ADD CONSTRAINT `gmb_posts_location_id_fkey` FOREIGN KEY (`location_id`) REFERENCES `gmb_locations` (`id`) ON DELETE CASCADE;
ALTER TABLE `gmb_review_replies` ADD CONSTRAINT `gmb_review_replies_review_id_fkey` FOREIGN KEY (`review_id`) REFERENCES `gmb_reviews` (`id`) ON DELETE CASCADE;
ALTER TABLE `gmb_review_replies` ADD CONSTRAINT `gmb_review_replies_template_id_fkey` FOREIGN KEY (`template_id`) REFERENCES `gmb_reply_templates` (`id`) ON DELETE SET NULL;
ALTER TABLE `gmb_reviews` ADD CONSTRAINT `gmb_reviews_location_id_fkey` FOREIGN KEY (`location_id`) REFERENCES `gmb_locations` (`id`) ON DELETE CASCADE;
ALTER TABLE `gmb_sync_logs` ADD CONSTRAINT `gmb_sync_logs_location_id_fkey` FOREIGN KEY (`location_id`) REFERENCES `gmb_locations` (`id`) ON DELETE CASCADE;
ALTER TABLE `journey_data` ADD CONSTRAINT `journey_data_contact_id_fkey` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `landing_design_presets` ADD CONSTRAINT `landing_design_presets_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
ALTER TABLE `landing_page_previews` ADD CONSTRAINT `landing_page_previews_version_id_fkey` FOREIGN KEY (`version_id`) REFERENCES `landing_page_versions` (`id`) ON DELETE CASCADE;
ALTER TABLE `lead_blockchain` ADD CONSTRAINT `lead_blockchain_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `lead_purchases` ADD CONSTRAINT `lead_purchases_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `lead_purchases` ADD CONSTRAINT `lead_purchases_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `lead_purchases` ADD CONSTRAINT `lead_purchases_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL;
ALTER TABLE `lead_referrals` ADD CONSTRAINT `lead_referrals_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `lead_referrals` ADD CONSTRAINT `lead_referrals_referred_to_firm_id_fkey` FOREIGN KEY (`referred_to_firm_id`) REFERENCES `firms` (`id`) ON DELETE SET NULL;
ALTER TABLE `lead_referrals` ADD CONSTRAINT `lead_referrals_referring_firm_id_fkey` FOREIGN KEY (`referring_firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `lead_statuses` ADD CONSTRAINT `lead_statuses_contact_id_fkey` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE SET NULL;
ALTER TABLE `lead_statuses` ADD CONSTRAINT `lead_statuses_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `leads` ADD CONSTRAINT `leads_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `campaigns` (`id`) ON DELETE SET NULL;
ALTER TABLE `leads` ADD CONSTRAINT `leads_duplicate_of_fkey` FOREIGN KEY (`duplicate_of`) REFERENCES `leads` (`id`) ON DELETE SET NULL;
ALTER TABLE `leads` ADD CONSTRAINT `leads_source_id_fkey` FOREIGN KEY (`source_id`) REFERENCES `lead_sources` (`id`) ON DELETE SET NULL;
ALTER TABLE `leads` ADD CONSTRAINT `leads_vertical_id_fkey` FOREIGN KEY (`vertical_id`) REFERENCES `industry_verticals` (`id`);
ALTER TABLE `market_pulse_watchlist` ADD CONSTRAINT `market_pulse_watchlist_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `meta_ad_sets` ADD CONSTRAINT `meta_ad_sets_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `meta_campaigns` (`id`) ON DELETE CASCADE;
ALTER TABLE `meta_ads` ADD CONSTRAINT `meta_ads_ad_set_id_fkey` FOREIGN KEY (`ad_set_id`) REFERENCES `meta_ad_sets` (`id`) ON DELETE CASCADE;
ALTER TABLE `meta_ai_logs` ADD CONSTRAINT `meta_ai_logs_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `meta_campaigns` (`id`) ON DELETE CASCADE;
ALTER TABLE `meta_campaign_analytics` ADD CONSTRAINT `meta_campaign_analytics_ad_id_fkey` FOREIGN KEY (`ad_id`) REFERENCES `meta_ads` (`id`) ON DELETE SET NULL;
ALTER TABLE `meta_campaign_analytics` ADD CONSTRAINT `meta_campaign_analytics_ad_set_id_fkey` FOREIGN KEY (`ad_set_id`) REFERENCES `meta_ad_sets` (`id`) ON DELETE SET NULL;
ALTER TABLE `meta_campaign_analytics` ADD CONSTRAINT `meta_campaign_analytics_campaign_id_fkey` FOREIGN KEY (`campaign_id`) REFERENCES `meta_campaigns` (`id`) ON DELETE CASCADE;
ALTER TABLE `meta_campaigns` ADD CONSTRAINT `meta_campaigns_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `notes` ADD CONSTRAINT `notes_contact_id_fkey` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE;
ALTER TABLE `notes` ADD CONSTRAINT `notes_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `notes` ADD CONSTRAINT `notes_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `notification_preferences` ADD CONSTRAINT `notification_preferences_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `platform_connections` ADD CONSTRAINT `platform_connections_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `platform_connections` ADD CONSTRAINT `platform_connections_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `profiles` ADD CONSTRAINT `profiles_id_fkey` FOREIGN KEY (`id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
ALTER TABLE `report_schedules` ADD CONSTRAINT `report_schedules_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `role_module_permissions` ADD CONSTRAINT `role_module_permissions_updated_by_fkey` FOREIGN KEY (`updated_by`) REFERENCES `users` (`id`);
ALTER TABLE `seo_issues` ADD CONSTRAINT `seo_issues_scan_id_fkey` FOREIGN KEY (`scan_id`) REFERENCES `seo_scans` (`id`) ON DELETE CASCADE;
ALTER TABLE `seo_thresholds` ADD CONSTRAINT `seo_thresholds_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `social_posts` ADD CONSTRAINT `social_posts_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `social_posts` ADD CONSTRAINT `social_posts_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`);
ALTER TABLE `team_members` ADD CONSTRAINT `team_members_team_id_fkey` FOREIGN KEY (`team_id`) REFERENCES `teams` (`id`) ON DELETE CASCADE;
ALTER TABLE `teams` ADD CONSTRAINT `teams_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `tort_types` ADD CONSTRAINT `tort_types_created_by_fkey` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`);
ALTER TABLE `tort_types` ADD CONSTRAINT `tort_types_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `touchpoints` ADD CONSTRAINT `touchpoints_contact_id_fkey` FOREIGN KEY (`contact_id`) REFERENCES `contacts` (`id`) ON DELETE CASCADE;
ALTER TABLE `touchpoints` ADD CONSTRAINT `touchpoints_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `touchpoints` ADD CONSTRAINT `touchpoints_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE SET NULL;
-- (auth.users ref) ALTER TABLE `user_roles` ADD CONSTRAINT `user_roles_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_ai_prompts` ADD CONSTRAINT `vertical_ai_prompts_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_ai_prompts` ADD CONSTRAINT `vertical_ai_prompts_vertical_id_fkey` FOREIGN KEY (`vertical_id`) REFERENCES `industry_verticals` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_intake_fields` ADD CONSTRAINT `vertical_intake_fields_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_intake_fields` ADD CONSTRAINT `vertical_intake_fields_vertical_id_fkey` FOREIGN KEY (`vertical_id`) REFERENCES `industry_verticals` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_lead_categories` ADD CONSTRAINT `vertical_lead_categories_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_lead_categories` ADD CONSTRAINT `vertical_lead_categories_vertical_id_fkey` FOREIGN KEY (`vertical_id`) REFERENCES `industry_verticals` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_module_access` ADD CONSTRAINT `vertical_module_access_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_module_access` ADD CONSTRAINT `vertical_module_access_vertical_id_fkey` FOREIGN KEY (`vertical_id`) REFERENCES `industry_verticals` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_pipeline_stages` ADD CONSTRAINT `vertical_pipeline_stages_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_pipeline_stages` ADD CONSTRAINT `vertical_pipeline_stages_vertical_id_fkey` FOREIGN KEY (`vertical_id`) REFERENCES `industry_verticals` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_terminology` ADD CONSTRAINT `vertical_terminology_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `vertical_terminology` ADD CONSTRAINT `vertical_terminology_vertical_id_fkey` FOREIGN KEY (`vertical_id`) REFERENCES `industry_verticals` (`id`) ON DELETE CASCADE;
ALTER TABLE `video_ad_projects` ADD CONSTRAINT `video_ad_projects_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `viral_content_library` ADD CONSTRAINT `viral_content_library_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `war_room_messages` ADD CONSTRAINT `war_room_messages_firm_id_fkey` FOREIGN KEY (`firm_id`) REFERENCES `firms` (`id`) ON DELETE CASCADE;
ALTER TABLE `war_room_messages` ADD CONSTRAINT `war_room_messages_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads` (`id`) ON DELETE CASCADE;
ALTER TABLE `wd_ai_activity` ADD CONSTRAINT `wd_ai_activity_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `wd_projects` (`id`) ON DELETE CASCADE;
ALTER TABLE `wd_audits` ADD CONSTRAINT `wd_audits_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `wd_projects` (`id`) ON DELETE CASCADE;
ALTER TABLE `wd_connectors` ADD CONSTRAINT `wd_connectors_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `wd_projects` (`id`) ON DELETE CASCADE;
ALTER TABLE `wd_findings` ADD CONSTRAINT `wd_findings_audit_id_fkey` FOREIGN KEY (`audit_id`) REFERENCES `wd_audits` (`id`) ON DELETE CASCADE;
ALTER TABLE `wd_findings` ADD CONSTRAINT `wd_findings_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `wd_projects` (`id`) ON DELETE CASCADE;
ALTER TABLE `wd_jobs` ADD CONSTRAINT `wd_jobs_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `wd_projects` (`id`) ON DELETE CASCADE;
ALTER TABLE `wd_monitor_events` ADD CONSTRAINT `wd_monitor_events_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `wd_projects` (`id`) ON DELETE CASCADE;
ALTER TABLE `wd_patches` ADD CONSTRAINT `wd_patches_finding_id_fkey` FOREIGN KEY (`finding_id`) REFERENCES `wd_findings` (`id`) ON DELETE SET NULL;
ALTER TABLE `wd_patches` ADD CONSTRAINT `wd_patches_project_id_fkey` FOREIGN KEY (`project_id`) REFERENCES `wd_projects` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `webauthn_challenges` ADD CONSTRAINT `webauthn_challenges_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
-- (auth.users ref) ALTER TABLE `webauthn_credentials` ADD CONSTRAINT `webauthn_credentials_user_id_fkey` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE;
