-- Auto-generated secondary indexes (PK + UNIQUE already in 0002).

CREATE INDEX `idx_document_signatures_lead` ON `document_signatures` (`lead_id`);
CREATE INDEX `idx_document_signatures_firm` ON `document_signatures` (`firm_id`);
CREATE INDEX `idx_gmb_locations_firm` ON `gmb_locations` (`firm_id`);
CREATE INDEX `idx_gmb_locations_google_account` ON `gmb_locations` (`google_account_id IS NOT NULL`);
CREATE INDEX `idx_recovery_codes_user_id` ON `recovery_codes` (`user_id`);
CREATE INDEX `idx_category_select_events_vertical_created` ON `category_select_events` (`vertical_slug`, `created_at`);
CREATE INDEX `idx_category_select_events_missing` ON `category_select_events` (`is_missing = true`);
CREATE INDEX `idx_landing_templates_user` ON `landing_page_templates` (`user_id`);
CREATE INDEX `idx_landing_templates_public` ON `landing_page_templates` (`is_public = true`);
CREATE INDEX `idx_landing_page_templates_starter` ON `landing_page_templates` (`is_starter`, `vertical_slug`);
CREATE INDEX `idx_seo_issues_scan` ON `seo_issues` (`scan_id`);
CREATE INDEX `idx_gmb_reply_templates_firm` ON `gmb_reply_templates` (`firm_id`);
CREATE INDEX `idx_wd_monitor_project` ON `wd_monitor_events` (`project_id`, `created_at`);
CREATE INDEX `idx_wd_ai_activity_project` ON `wd_ai_activity` (`project_id`, `created_at`);
CREATE INDEX `idx_lead_blockchain_lead_id` ON `lead_blockchain` (`lead_id`);
CREATE INDEX `idx_lead_blockchain_created_at` ON `lead_blockchain` (`created_at`);
CREATE INDEX `idx_touchpoints_contact_id` ON `touchpoints` (`contact_id`);
CREATE INDEX `idx_touchpoints_firm_id` ON `touchpoints` (`firm_id`);
CREATE INDEX `idx_wd_audits_project` ON `wd_audits` (`project_id`, `created_at`);
CREATE INDEX `idx_notes_lead_id` ON `notes` (`lead_id`);
CREATE INDEX `idx_notes_contact_id` ON `notes` (`contact_id`);
CREATE INDEX `idx_vps_vertical` ON `vertical_pipeline_stages` (`vertical_id`);
CREATE INDEX `idx_vps_firm` ON `vertical_pipeline_stages` (`firm_id`);
CREATE INDEX `idx_vap_lookup` ON `vertical_ai_prompts` (`is_active = true`);
CREATE INDEX `idx_ai_seo_runs_firm_tool` ON `ai_seo_runs` (`firm_id`, `tool`, `created_at`);
CREATE INDEX `idx_ai_seo_runs_user` ON `ai_seo_runs` (`user_id`, `created_at`);
CREATE INDEX `idx_seo_scans_firm` ON `seo_scans` (`firm_id`, `created_at`);
CREATE INDEX `idx_wd_projects_firm` ON `wd_projects` (`firm_id`);
CREATE INDEX `idx_wd_projects_domain` ON `wd_projects` (`normalized_domain`);
CREATE INDEX `idx_landing_domains_firm` ON `landing_page_domains` (`firm_id`);
CREATE INDEX `idx_landing_domains_hostname` ON `landing_page_domains` (`hostname`);
CREATE INDEX `idx_vertical_module_access_lookup` ON `vertical_module_access` (`firm_id IS NULL`);
CREATE INDEX `idx_vma_lookup` ON `vertical_module_access` (`vertical_id`, `module_key`);
CREATE INDEX `idx_wd_jobs_pickup` ON `wd_jobs` (`status`, `run_after`);
CREATE INDEX `idx_meta_ai_logs_campaign_id` ON `meta_ai_logs` (`campaign_id`);
CREATE INDEX `idx_meta_ads_ad_set_id` ON `meta_ads` (`ad_set_id`);
CREATE INDEX `idx_meta_analytics_campaign_id` ON `meta_campaign_analytics` (`campaign_id`);
CREATE INDEX `idx_meta_analytics_date` ON `meta_campaign_analytics` (`date`);
CREATE INDEX `idx_journey_data_contact_id` ON `journey_data` (`contact_id`);
CREATE INDEX `idx_chat_participants_user` ON `chat_participants` (`user_id`);
CREATE INDEX `idx_lead_statuses_lead_id` ON `lead_statuses` (`lead_id`);
CREATE INDEX `idx_lead_purchases_pipeline_stage` ON `lead_purchases` (`pipeline_stage`);
CREATE INDEX `idx_landing_design_presets_user` ON `landing_design_presets` (`user_id`, `created_at`);
CREATE INDEX `idx_meta_campaigns_firm_id` ON `meta_campaigns` (`firm_id`);
CREATE INDEX `idx_meta_ad_sets_campaign_id` ON `meta_ad_sets` (`campaign_id`);
CREATE INDEX `idx_ai_tool_results_firm_tool` ON `ai_tool_results` (`firm_id`, `tool_key`, `created_at`);
CREATE INDEX `idx_ai_tool_results_user` ON `ai_tool_results` (`user_id`, `created_at`);
CREATE INDEX `idx_filter_rejection_logs_field` ON `filter_rejection_logs` (`field`);
CREATE INDEX `idx_filter_rejection_logs_vertical` ON `filter_rejection_logs` (`vertical_slug`);
CREATE INDEX `idx_filter_rejection_logs_created_at` ON `filter_rejection_logs` (`created_at`);
CREATE INDEX `idx_filter_rejection_logs_firm_id` ON `filter_rejection_logs` (`firm_id`);
CREATE INDEX `idx_contacts_firm_id` ON `contacts` (`firm_id`);
CREATE INDEX `idx_contacts_email` ON `contacts` (`email`);
CREATE INDEX `idx_contacts_phone` ON `contacts` (`phone`);
CREATE INDEX `idx_contacts_status` ON `contacts` (`status`);
CREATE INDEX `idx_gmb_oauth_consents_firm` ON `gmb_oauth_consents` (`firm_id`, `created_at`);
CREATE INDEX `idx_leads_vertical` ON `leads` (`vertical_id`);
CREATE INDEX `idx_leads_source_id` ON `leads` (`source_id`);
CREATE INDEX `idx_leads_external_id` ON `leads` (`external_id`);
CREATE INDEX `idx_wd_connectors_project` ON `wd_connectors` (`project_id`);
CREATE INDEX `idx_fraud_checks_lead_id` ON `fraud_checks` (`lead_id`);
CREATE INDEX `idx_fraud_checks_check_type` ON `fraud_checks` (`check_type`);
CREATE INDEX `idx_fraud_checks_severity` ON `fraud_checks` (`severity`);
CREATE INDEX `idx_lpv_firm` ON `landing_page_versions` (`firm_id`, `created_at`);
CREATE INDEX `idx_crm_sync_logs_integration` ON `crm_sync_logs` (`integration_id`);
CREATE INDEX `idx_crm_sync_logs_status` ON `crm_sync_logs` (`status`);
CREATE INDEX `idx_competitor_ad_runs_firm` ON `competitor_ad_runs` (`firm_id`, `created_at`);
CREATE INDEX `idx_competitor_ad_creatives_run` ON `competitor_ad_creatives` (`run_id`);
CREATE INDEX `idx_gmb_account_links_firm` ON `gmb_account_links` (`firm_id`);
CREATE INDEX `idx_crm_integrations_firm` ON `crm_integrations` (`firm_id`);
CREATE INDEX `idx_chat_messages_conversation` ON `chat_messages` (`conversation_id`, `created_at`);
CREATE INDEX `idx_lead_activity_logs_lead_id` ON `lead_activity_logs` (`lead_id`);
CREATE INDEX `idx_lead_activity_logs_firm_id` ON `lead_activity_logs` (`firm_id`);
CREATE INDEX `idx_lead_activity_logs_created_at` ON `lead_activity_logs` (`created_at`);
CREATE INDEX `idx_firms_vertical` ON `firms` (`vertical_id`);
CREATE INDEX `idx_wd_patches_project` ON `wd_patches` (`project_id`, `status`);
CREATE INDEX `idx_wd_findings_project` ON `wd_findings` (`project_id`, `severity`, `status`);
CREATE INDEX `idx_wd_findings_audit` ON `wd_findings` (`audit_id`);
CREATE INDEX `idx_gmb_sync_logs_firm` ON `gmb_sync_logs` (`firm_id`, `started_at`);
CREATE INDEX `idx_gmb_sync_logs_location` ON `gmb_sync_logs` (`location_id`, `started_at`);
CREATE INDEX `idx_vif_vertical` ON `vertical_intake_fields` (`vertical_id`);
CREATE INDEX `idx_vif_firm` ON `vertical_intake_fields` (`firm_id`);
CREATE INDEX `idx_vlc_vertical` ON `vertical_lead_categories` (`vertical_id`);
CREATE INDEX `idx_lpp_firm` ON `landing_page_previews` (`firm_id`, `created_at`);
CREATE INDEX `idx_lpp_token` ON `landing_page_previews` (`token`);
CREATE INDEX `idx_gmb_review_replies_firm` ON `gmb_review_replies` (`firm_id`, `status`);
CREATE INDEX `idx_gmb_review_replies_review` ON `gmb_review_replies` (`review_id`);
